name = "ryan/project_template"
version = "0.1.0"
description = "roblox project template designed to speed up the development process"
authors = ["ryan"]
repository = "https://github.com/ryansreality/project-template"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
remo = { wally = "wally#littensy/remo", version = "^1.5.1" }
vide = { wally = "wally#centau/vide", version = "^0.3.1" }
lapis = { wally = "wally#nezuo/lapis", version = "^0.3.3" }
charm = { wally = "wally#littensy/charm", version = "^0.9.0" }
charm-sync = { wally = "wally#littensy/charm-sync", version = "^0.2.0" }
