[package]
name = "ryan/template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
remo = "littensy/remo@1.5.0"
vide = "centau/vide@0.3.1"
lapis = "nezuo/lapis@0.3.3"
charm = "littensy/charm@0.8.1"
charm_sync = "littensy/charm-sync@0.1.1"
