name = "jiwonz/pathfs"
version = "0.1.0"
description = "luau-path + @lune/fs"
license = "MIT"
authors = ["jeparlefrancais <jeparlefrancais21@gmail.com>", "jiwonz"]
repository = "https://github.com/jiwonz/lune-path-fs/"
private = false
includes = ["README.md", "init.luau", "luau-path.luau", "pesde.toml", "types"]

[target]
environment = "lune"
lib = "init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
